# Generated by Django 4.0.4 on 2022-04-29 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nowa_aplikacja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roslina',
            name='dni_siewki',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roslina',
            name='nazwa_rosliny',
            field=models.CharField(blank=True, max_length=60, null=True, unique=True),
        ),
    ]
