# Generated by Django 4.0.4 on 2022-04-29 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nowa_aplikacja', '0002_roslina_dni_siewki_alter_roslina_nazwa_rosliny'),
    ]

    operations = [
        migrations.AddField(
            model_name='roslina',
            name='trudnosc_uprawy',
            field=models.CharField(blank=True, choices=[('1', 'Łatwy'), ('2', 'Średni'), ('3', 'Trudny')], default='2', max_length=8),
        ),
    ]
