# Generated by Django 4.0.4 on 2022-04-29 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nowa_aplikacja', '0003_roslina_trudnosc_uprawy'),
    ]

    operations = [
        migrations.AddField(
            model_name='roslina',
            name='obraz',
            field=models.ImageField(null=True, upload_to='zdjęcia'),
        ),
        migrations.AddField(
            model_name='roslina',
            name='wysokosc',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
